// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/zakiyalmaya/hotel-management/model"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// Login provides a mock function with given fields: request
func (_m *AuthService) Login(request *model.AuthRequest) (*model.AuthResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.AuthRequest) (*model.AuthResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(*model.AuthRequest) *model.AuthResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.AuthRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: username
func (_m *AuthService) Logout(username string) error {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshAuthToken provides a mock function with given fields: username
func (_m *AuthService) RefreshAuthToken(username string) (*model.AuthResponse, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAuthToken")
	}

	var r0 *model.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.AuthResponse, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *model.AuthResponse); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
